const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
const ADD_EDIT_USER_SUCCESS = "ADD_EDIT_USER_SUCCESS";
const FETCH_SESSION_SUCCESS = "FETCH_SESSION_SUCCESS";
const ADD_USER = "ADD_USER";
const EDIT_USER = "EDIT_USER";
const DELETE_USER = "DELETE_USER";

export {
  ADD_USER,
  EDIT_USER,
  DELETE_USER,
  FETCH_USER_SUCCESS,
  FETCH_SESSION_SUCCESS,
  ADD_EDIT_USER_SUCCESS,
};
